---
title: "Stats 140SL - EDA"
author: "Ritesh Pendekanti"
date: "November 21, 2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Data and fix date formatting
```{r}
library(lubridate)

# Load data
reddit_comments <- read.csv('data/reddit_clean_comments.csv')
reddit_posts <- read.csv('data/reddit_clean_posts.csv')
google <- read.csv('data/google_trends.csv')[-c(1:6),]
prices <- read.csv('data/TSLA.csv')

# Fix date formatting
reddit_comments$Date <- date(as_datetime(reddit_comments$created_utc))
google$Date <- mdy(google$Date)
reddit_posts$Date <- date(as_datetime(reddit_posts$created_utc))
prices$Date <- ymd(prices$Date)
```

## Explore Google Trends
The original data is positively skewed so we transform the data using the square root function. 
```{r}
library(ggplot2)
ggplot(google, aes(x=sqrt(Tesla)))+
  geom_histogram(color="darkblue", fill="lightblue") + 
  ggtitle("Histogram of Google Trend Data") + 
  xlab("Google Trend Search Score")
```

## Explore Reddit Posts
```{r}
head(reddit_posts)
```

Let's create a new variable called "weighted_sentiment" since each post has a different score associated with it. 
```{r}
reddit_posts$weighted_sentiment <- reddit_posts$score * reddit_posts$sentiment
reddit_posts_df <- aggregate(weighted_sentiment ~ Date, data = reddit_posts, mean)
reddit_comments$weighted_sentiment <- reddit_comments$score * reddit_comments$sentiment
reddit_comments_df <- aggregate(weighted_sentiment ~ Date, data = reddit_comments, mean)
# hist(sqrt(reddit_comments_df$weighted_sentiment + 2), main = "Reddit Comments Weighted Sentiment")
# hist(reddit_posts_df$weighted_sentiment, main = "Reddit Posts Weighted Sentiment")
```

Prepare data for time series plotting
```{r}
range01 <- function(x){(x-min(x))/(max(x)-min(x))}
df <- merge(google[,c('Date', 'Tesla')], 
            prices[, c('Date', 'Close')], 
            by = 'Date')
df <- merge(df, reddit_comments_df, by = 'Date')
```

Plot
```{r}
df_plot <- df[-c(1:93),]

# Value used to transform the data
coeff <- 5

# A few constants
googleTrendColor <- "#69b3a2"
priceColor <- rgb(0.2, 0.6, 0.9, 1)

ggplot(df_plot, aes(x=Date)) +
  
  geom_line( aes(y=Tesla), size=1, color=googleTrendColor) + 
  geom_line( aes(y=Close / coeff), size=1, color=priceColor) +
  
  scale_y_continuous(
    
    # Features of the first axis
    name = "Google Trend",
    
    # Add a second axis and specify its features
    sec.axis = sec_axis(~.*coeff, name="Price ($)")
  ) + 

  theme(
    axis.title.y = element_text(color = googleTrendColor, size=13),
    axis.title.y.right = element_text(color = priceColor, size=13)
  ) +

  ggtitle("Google Trend vs Tesla Stock Price")
```

```{r}
# Value used to transform the data
coeff <- 100

# A few constants
redditColor <- 'red'
priceColor <- rgb(0.2, 0.6, 0.9, 1)

ggplot(df_plot, aes(x=Date)) +
  
  geom_line( aes(y=weighted_sentiment), size=1, color=redditColor) + 
  geom_line( aes(y=Close / coeff), size=1, color=priceColor) +
  
  scale_y_continuous(
    
    # Features of the first axis
    name = "Reddit Sentiment",
    
    # Add a second axis and specify its features
    sec.axis = sec_axis(~.*coeff, name="Price ($)")
  ) + 

  theme(
    axis.title.y = element_text(color = redditColor, size=13),
    axis.title.y.right = element_text(color = priceColor, size=13)
  ) +

  ggtitle("Reddit Sentiment vs Tesla Stock Price")
```