---
title: "Backtest Algorithm"
author: "Ritesh Pendekanti"
date: "November 28, 2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Data 

```{r}
library(tidyverse)
library(tidyquant)  

options("getSymbols.warning4.0"=FALSE)
options("getSymbols.yahoo.warning"=FALSE)
getSymbols("TSLA", from = '2019-08-01',
           to = "2020-11-15",warnings = FALSE,
           auto.assign = TRUE)
```

```{r}
head(TSLA)
dates <- as.Date(c("2019-08-01", "2020-01-03", "2020-10-01", "2020-11-03"))
action <- c("buy", "sell", "buy", "sell")
df <- data.frame(dates = dates, action = action)
```

```{r}
backTest <- function(prices, df){
  if(!all(colnames(df) == c('dates', 'action'))){
    return("Error: Invalid Data Frame Format.")
  }
  
  # Get only rows that we buy or sell from.
  relevant_prices <- prices[df$dates,]
  
  # Initialize starting investment of $1000.
  investment <- 1000
  q <- 0
  print(paste0("Initializing investment at $", investment))
  print("------------------------")
  
  # Begin backtesting
  for (i in seq_along(1:nrow(df))){
    p <- as.numeric(prices[df$dates[i], 6])
    if(length(p) == 0){
      return(paste0("Error: Invalid Date: ", 
                    df$dates[i],
                    ". Make sure none of the dates are weekends."))
    }
    print(paste0("Date: ", df$dates[i]))
    if(df$action[i] == 'buy'){
      q <- q + floor(investment/p)
      investment <- investment - (p*q)
      print(paste0("Bought ", q, " at $", p))
      print(paste0("Investment total: $", round(investment, 2)))
    } else {
      investment <- investment + (p*q)
      print(paste0("Sold ", q, " at $", p))
      print(paste0("Investment total: $", round(investment, 2)))
      q <- 0
    }
    print("------------------------")
  }
  
  print(paste0("Final Amount: $", investment))
  print(paste0("Percentage Yield: ", round((investment/1000), 2) * 100, "%"))
  return (investment)
}
```

```{r}
backTest(TSLA, df)
```
